matchers:
  - subnets:
    - 10.2.1.1/32
    - 10.2.1.2/32
    secret: RADIUS_SECRET_MIKROTIK
    mapper: mikrotik
  - subnets:
    - 10.1.12.1/32
    secret: RADIUS_SECRET_SUPERMICRO
    mapper: supermicro
  - subnets:
    - 10.1.11.2/32
    secret: RADIUS_SECRET_APCUPS
    mapper: apc
  - subnets:
    - 10.1.11.3/32
    secret: RADIUS_SECRET_CYBERPOWER
    mapper: cyberpower

radius:
  token_expiry: 1h

oauth:
  user_info_url: https://example.com/oauth/userinfo
  token_url: https://example.com/oauth/token
  auth_url: https://example.com/oauth/auth
  redirect_url: https://example.com/oauth/redirect
  scopes:
    - openid
    - profile
    - email
  client_id: YOUR_CLIENT_ID
  client_secret: YOUR_CLIENT_SECRET
  server_addr: "127.0.0.1:8080"
