matchers:
  - subnets:
    - 10.2.1.1/32
    - 10.2.1.2/32
    secret: ${RADIUS_SECRET_MIKROTIK}
    mapper: mikrotik
  - subnets:
    - 10.1.12.1/32
    secret: ${RADIUS_SECRET_SUPERMICRO}
    mapper: supermicro
  - subnets:
    - 10.1.11.2/32
    secret: ${RADIUS_SECRET_APCUPS}
    mapper: apc
  - subnets:
    - 10.1.11.3/32
    secret: ${RADIUS_SECRET_CYBERPOWER}
    mapper: cyberpower

radius:
  token_expiry: 1h

oauth:
  userinfo_url: ${OAUTH_USERINFO_URL}
  token_url: ${OAUTH_TOKEN_URL}
  auth_url: ${OAUTH_AUTH_URL}
  redirect_url: ${OAUTH_REDIRECT_URL}
  scopes:
    - openid
    - profile
    - email
  client_id: ${OAUTH_CLIENT_ID}
  client_secret: ${OAUTH_CLIENT_SECRET}
  server_addr: ${OAUTH_SERVER_ADDR}
