name: Test and lint
on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_call: {}
jobs:
  test:
    name: Test and lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '>=1.19.0'
          check-latest: true
          cache: false
      - name: Fix go.mod
        run: go mod tidy
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest  
      - name: Run tests
        run: go test -race=1 -v ./...
